{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "636a4d3b-5dee-44b7-9ac9-a67bce2f71c2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Gurobi Optimizer version 12.0.3 build v12.0.3rc0 (mac64[arm] - Darwin 24.6.0 24G90)\n",
      "\n",
      "CPU model: Apple M4\n",
      "Thread count: 10 physical cores, 10 logical processors, using up to 10 threads\n",
      "\n",
      "Optimize a model with 38 rows, 162 columns and 648 nonzeros\n",
      "Model fingerprint: 0xd5b41073\n",
      "Variable types: 0 continuous, 162 integer (162 binary)\n",
      "Coefficient statistics:\n",
      "  Matrix range     [1e+00, 1e+00]\n",
      "  Objective range  [2e+01, 7e+02]\n",
      "  Bounds range     [1e+00, 1e+00]\n",
      "  RHS range        [1e+00, 1e+01]\n",
      "Found heuristic solution: objective 5245.7833334\n",
      "Presolve removed 1 rows and 0 columns\n",
      "Presolve time: 0.00s\n",
      "Presolved: 37 rows, 162 columns, 630 nonzeros\n",
      "Variable types: 0 continuous, 162 integer (162 binary)\n",
      "\n",
      "Root relaxation: objective 7.131817e+03, 38 iterations, 0.00 seconds (0.00 work units)\n",
      "\n",
      "    Nodes    |    Current Node    |     Objective Bounds      |     Work\n",
      " Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time\n",
      "\n",
      "*    0     0               0    7131.8166667 7131.81667  0.00%     -    0s\n",
      "\n",
      "Explored 1 nodes (38 simplex iterations) in 0.01 seconds (0.00 work units)\n",
      "Thread count was 10 (of 10 available processors)\n",
      "\n",
      "Solution count 2: 7131.82 5245.78 \n",
      "\n",
      "Optimal solution found (tolerance 1.00e-04)\n",
      "Best objective 7.131816666700e+03, best bound 7.131816666700e+03, gap 0.0000%\n",
      "\n",
      "Optimal objective value (total expected points): 7131.82\n",
      "\n",
      "Draft plan (round -> position):\n",
      "  Round 1: SP (X[1,8] = 1)\n",
      "  Round 2: SP (X[2,8] = 1)\n",
      "  Round 3: 3B (X[3,3] = 1)\n",
      "  Round 4: 1B (X[4,1] = 1)\n",
      "  Round 5: SP (X[5,8] = 1)\n",
      "  Round 6: 1B (X[6,1] = 1)\n",
      "  Round 7: OF (X[7,6] = 1)\n",
      "  Round 8: C (X[8,5] = 1)\n",
      "  Round 9: SS (X[9,4] = 1)\n",
      "  Round 10: RP (X[10,9] = 1)\n",
      "  Round 11: RP (X[11,9] = 1)\n",
      "  Round 12: SP (X[12,8] = 1)\n",
      "  Round 13: SP (X[13,8] = 1)\n",
      "  Round 14: 2B (X[14,2] = 1)\n",
      "  Round 15: SP (X[15,8] = 1)\n",
      "  Round 16: OF (X[16,6] = 1)\n",
      "  Round 17: DH (X[17,7] = 1)\n",
      "  Round 18: OF (X[18,6] = 1)\n"
     ]
    }
   ],
   "source": [
    "import gurobipy as gp\n",
    "from gurobipy import GRB\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import sys\n",
    "\n",
    "csv_file_path = '/Users/harperstrickland/Downloads/PositionRoundAverages (1).csv'\n",
    "df = pd.read_csv(csv_file_path)\n",
    "\n",
    "pos_names = {\n",
    "    1: \"1B\",\n",
    "    2: \"2B\",\n",
    "    3: \"3B\",\n",
    "    4: \"SS\",\n",
    "    5: \"C\",\n",
    "    6: \"OF\",\n",
    "    7: \"DH\",\n",
    "    8: \"SP\",\n",
    "    9: \"RP\"\n",
    "}\n",
    "\n",
    "meta_cols = ['Position', 'Round']\n",
    "\n",
    "all_value_cols = [c for c in df.columns if c not in meta_cols]\n",
    "\n",
    "value_cols = all_value_cols[:9]\n",
    "\n",
    "values = df[value_cols].apply(pd.to_numeric, errors='coerce')\n",
    "\n",
    "value_cols = df.columns[1:]\n",
    "\n",
    "values = values.iloc[:18, :9]\n",
    "if not np.isfinite(values.to_numpy()).all():\n",
    "    raise ValueError(\"Numeric data still has NaN/Inf; please clean the CSV.\")\n",
    "\n",
    "n_rounds = values.shape[0]     \n",
    "n_positions = values.shape[1]  \n",
    "\n",
    "rounds = range(1, n_rounds + 1)         \n",
    "positions = range(1, n_positions + 1)\n",
    "\n",
    "P = {}\n",
    "for i in rounds:            \n",
    "    for j in positions:     \n",
    "        P[(i, j)] = float(values.iloc[i - 1, j - 1])\n",
    "\n",
    "\n",
    "m = gp.Model(\"Fantasy_Baseball_Draft_Optimization\")\n",
    "\n",
    "X = m.addVars(rounds, positions, vtype=GRB.BINARY, name=\"X\")\n",
    "\n",
    "m.setObjective(\n",
    "    gp.quicksum(P[(i, j)] * X[i, j] for i in rounds for j in positions),\n",
    "    GRB.MAXIMIZE\n",
    ")\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# Constraints\n",
    "# -----------------------------\n",
    "\n",
    "# Draft constraint\n",
    "for i in rounds:\n",
    "    m.addConstr(gp.quicksum(X[i, j] for j in positions) == 1)\n",
    "\n",
    "# Infield and catcher\n",
    "for j in range(1, 6):\n",
    "    m.addConstr(gp.quicksum(X[i, j] for i in rounds) >= 1)\n",
    "    m.addConstr(gp.quicksum(X[i, j] for i in rounds) <= 3)\n",
    "\n",
    "# Outfield\n",
    "m.addConstr(gp.quicksum(X[i, 6] for i in rounds) >= 3)\n",
    "m.addConstr(gp.quicksum(X[i, 6] for i in rounds) <= 5)\n",
    "\n",
    "# Designated hitter\n",
    "m.addConstr(gp.quicksum(X[i, 7] for i in rounds) >= 0)\n",
    "m.addConstr(gp.quicksum(X[i, 7] for i in rounds) <= 2)\n",
    "\n",
    "# Total position players\n",
    "m.addConstr(\n",
    "    gp.quicksum(X[i, 1] for i in rounds) +\n",
    "    gp.quicksum(X[i, 2] for i in rounds) +\n",
    "    gp.quicksum(X[i, 3] for i in rounds) +\n",
    "    gp.quicksum(X[i, 4] for i in rounds) +\n",
    "    gp.quicksum(X[i, 5] for i in rounds) +\n",
    "    gp.quicksum(X[i, 6] for i in rounds) +\n",
    "    gp.quicksum(X[i, 7] for i in rounds) \n",
    "    == 10\n",
    ")\n",
    "\n",
    "# Starting pitchers\n",
    "m.addConstr(gp.quicksum(X[i, 8] for i in rounds) >= 2, name=\"SP_Min\")\n",
    "m.addConstr(gp.quicksum(X[i, 8] for i in rounds) <= 6, name=\"SP_Max\")\n",
    "\n",
    "# Bullpen pitchers\n",
    "m.addConstr(gp.quicksum(X[i, 9] for i in rounds) >= 2, name=\"RP_Min\")\n",
    "m.addConstr(gp.quicksum(X[i, 9] for i in rounds) <= 6, name=\"RP_Max\")\n",
    "\n",
    "\n",
    "\n",
    "# Total pitchers\n",
    "m.addConstr(\n",
    "    gp.quicksum(X[i, 8] for i in rounds) +\n",
    "    gp.quicksum(X[i, 9] for i in rounds) \n",
    "    == 8\n",
    ")\n",
    "\n",
    "#------------------\n",
    "#End Constraints\n",
    "#------------------\n",
    "\n",
    "m.optimize()\n",
    "\n",
    "\n",
    "if m.status == GRB.OPTIMAL:\n",
    "    print(f\"\\nOptimal objective value (total expected points): {m.objVal:.2f}\\n\")\n",
    "    print(\"Draft plan (round -> position):\")\n",
    "    for i in rounds:\n",
    "        for j in positions:\n",
    "            if X[i, j].X > 0.5:  \n",
    "                print(f\"  Round {i}: {pos_names[j]} (X[{i},{j}] = 1)\")\n",
    "else:\n",
    "    print(\"No optimal solution found. Model status:\", m.status)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "d54174f4-0640-4515-a0ab-bc189fb33441",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Gurobi Optimizer version 12.0.3 build v12.0.3rc0 (mac64[arm] - Darwin 24.6.0 24G90)\n",
      "\n",
      "CPU model: Apple M4\n",
      "Thread count: 10 physical cores, 10 logical processors, using up to 10 threads\n",
      "\n",
      "Optimize a model with 38 rows, 162 columns and 648 nonzeros\n",
      "Model fingerprint: 0x4a47bb82\n",
      "Variable types: 0 continuous, 162 integer (162 binary)\n",
      "Coefficient statistics:\n",
      "  Matrix range     [1e+00, 1e+00]\n",
      "  Objective range  [2e+01, 7e+02]\n",
      "  Bounds range     [1e+00, 1e+00]\n",
      "  RHS range        [1e+00, 1e+01]\n",
      "\n",
      "Loaded MIP start from previous solve with objective 7096.82\n",
      "\n",
      "Presolve removed 1 rows and 0 columns\n",
      "Presolve time: 0.00s\n",
      "Presolved: 37 rows, 162 columns, 630 nonzeros\n",
      "Variable types: 0 continuous, 162 integer (162 binary)\n",
      "\n",
      "Root relaxation: cutoff, 40 iterations, 0.00 seconds (0.00 work units)\n",
      "\n",
      "    Nodes    |    Current Node    |     Objective Bounds      |     Work\n",
      " Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time\n",
      "\n",
      "     0     0     cutoff    0      7096.81667 7096.81667  0.00%     -    0s\n",
      "\n",
      "Explored 1 nodes (40 simplex iterations) in 0.01 seconds (0.00 work units)\n",
      "Thread count was 10 (of 10 available processors)\n",
      "\n",
      "Solution count 1: 7096.82 \n",
      "\n",
      "Optimal solution found (tolerance 1.00e-04)\n",
      "Best objective 7.096816666700e+03, best bound 7.096816666700e+03, gap 0.0000%\n",
      "Total Expected Fantasy Points: 7096.8166667\n",
      "Draft Order: ['SP', 'SP', '3B', '1B', 'SP', '1B', 'OF', 'C', 'SS', 'RP', 'RP', 'SP', 'SP', '2B', 'RP', 'OF', 'DH', 'OF']\n",
      "Number of Starting Pitchers: 5, Number of Bullpen Pitchers: 3\n"
     ]
    }
   ],
   "source": [
    "# New scenario with a maximum of 5 starting pitchers and minimum of 3 bullpen pitchers. \n",
    "# Compared to our original optimal model, we are exchanging one starting pitcher for one bullpen pitcher.\n",
    "\n",
    "new_scenario = {\"SP_Max\": 5, \"RP_Min\": 3}\n",
    "\n",
    "# update constraints\n",
    "for constraint_name, new_rhs in new_scenario.items():\n",
    "    constraint = m.getConstrByName(constraint_name)\n",
    "    if constraint is not None:\n",
    "        constraint.RHS = new_rhs\n",
    "m.update()\n",
    "\n",
    "m.setObjective(\n",
    "    gp.quicksum(P[(i, j)] * X[i, j] for i in rounds for j in positions),\n",
    "    GRB.MAXIMIZE\n",
    ")\n",
    "m.optimize()\n",
    "\n",
    "if m.status == GRB.OPTIMAL:\n",
    "    draft_order = [pos_names[j] for i in rounds for j in positions if X[i, j].X > 0.5]\n",
    "    count_SP = draft_order.count('SP')\n",
    "    count_RP = draft_order.count('RP')\n",
    "\n",
    "    print(f\"Total Expected Fantasy Points: {m.objVal}\")\n",
    "    print(f\"Draft Order: {draft_order}\")\n",
    "    print(f\"Number of Starting Pitchers: {count_SP}, Number of Bullpen Pitchers: {count_RP}\")\n",
    "else:\n",
    "    print(\"No optimal solution found for this scenario.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
